### ISSUE TITLE
'@babel/runtime/helpers/builtin/interopRequireDefault' 

### ISSUE THREAD

**Issue by Charles-Hamilton** [stellarguard/stellarguard#31]
I have set up the program within a docker image (because my operating system is windows) and I face with the following error :
```
stellarguard_1  | Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'
stellarguard_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
stellarguard_1  |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
stellarguard_1  |     at Module.require (internal/modules/cjs/loader.js:690:17)
stellarguard_1  |     at require (internal/modules/cjs/helpers.js:25:18)
stellarguard_1  |     at Object.<anonymous> (/app/node_modules/yup/lib/index.js:3:30)
stellarguard_1  |     at Module._compile (internal/modules/cjs/loader.js:776:30)
stellarguard_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
stellarguard_1  |     at Module.load (internal/modules/cjs/loader.js:653:32)
stellarguard_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
stellarguard_1  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
stellarguard_1  | Program node ./src/server/bin/www exited with code 1
stellarguard_1  |
stellarguard_1  | Starting child process with 'node ./src/server/bin/www'

```

after a couple of searching I found  that's a problem with internal modules of material ui , and doesn't matter which version, have any body encountered with such  problem ?

**Comment by pselden** [comment]
Can you share your Dockerfile? I’ll look into what’s happening. There’s a new version of material-ui that might help too.

**Comment by z-hamidi** [comment]
@Charles-Hamilton
i have the same problem without docker. i executed it with npm install and get this error!`
Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'  `

**Comment by pselden** [comment]
I think it is some conflicting dependencies, but I can’t understand why it does not happen for me. Do you also use windows?

**Comment by z-hamidi** [comment]
no, now i use linux!
